{% set version = "2.0.10" %}

package:
  name: bob.ip.base
  version: {{ version }}

source:
  fn: bob.ip.base-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.ip.base/bob.ip.base-{{ version }}.zip
  md5: 3a977186c9da90e146b741ba08243342

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - python
    - setuptools
    - matplotlib
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.sp
    - bob.io.base
    - bob.math
    - vlfeat
    - boost 1.61.*
    - cmake
    - pkg-config

  run:
    - python
    - matplotlib
    - bob.extension
    - bob.blitz
    - bob.core
    - bob.sp
    - bob.io.base
    - bob.math
    - vlfeat
    - boost 1.61.*

test:
  commands:
    - nosetests -sv bob.ip.base

  imports:
    - bob
    - bob.ip
    - bob.ip.base
    - bob.ip.base.test

  requires:
    - nose

about:
  home: http://github.com/bioidiap/bob.ip.base
  license: Modified BSD License (3-clause)
  summary: Basic Image Processing Utilities for Bob

extra:
  recipe-maintainers:
    - 183amir
